---
- name: EC2 instance ##create ec2
  amazon.aws.ec2_instance:
    name: "{{ AWS_PREFIX }}_APP"
    vpc_subnet_id: "{{ aws_subnet_info.subnet.id }}"
    instance_type: t2.micro
    security_group: "{{ aws_groups_app.group_id }}"
    key_name: <pem_key>
    #chekc ami in aws website, or can use this but only valid in us-west-2
    image_id: ami-08675cddb6910220a
    state: running
    tags:
      Course: "{{ AWS_PREFIX }}"
      Role: "APP"
    network:
      assign_public_ip: true
  register: ec2_instance_data
  tags: 
    - provision

- name: DB EC2 instance ##create ec2
  amazon.aws.ec2_instance:
    name: "{{ AWS_PREFIX }}_DB"
    vpc_subnet_id: "{{ aws_subnet_info.subnet.id }}"
    instance_type: t2.micro
    security_group: "{{ aws_groups_db.group_id }}"
    key_name: <pem_key>
    #chekc ami in aws website, or can use this but only valid in us-west-2
    image_id: ami-08675cddb6910220a
    state: running
    tags:
      Course: "{{ AWS_PREFIX }}"
      Role: "DB"
    network:
      assign_public_ip: true
  register: ec2_instance_data
  tags: 
    - provision
  when: rds_database == false

# - name: EC2 instance ##create ec2
#   amazon.aws.ec2_instance:
#     name: "{{ AWS_PREFIX }}_{{item.name}}"
#     vpc_subnet_id: "{{ aws_db_subnet.subnets[0].id }}"
#     instance_type: t2.micro
#     security_group: "{{ item.group.security_groups[0].group_id }}"
#     key_name: <pem_key>
#     #chekc ami in aws website, or can use this but only valid in us-west-2
#     image_id: ami-08675cddb6910220a
#     tags:
#       Course: "{{ AWS_PREFIX }}"
#       Role: "{{ item.name }}"
#     network:
#       assign_public_ip: true
#   register: ec2_instance_data
#   tags:
#     - provision
#   loop:
#     - { group: "{{aws_groups_app}}", name: APP }
#     - { group: "{{aws_groups_db}}", name: DB }
#   when: rds_database == false
